---
- name: Rulebook to print debug message based on webhook event
  hosts: all
  gather_facts: false

  sources:
      - ansible.eda.webhook:
          host: 172.31.235.61
          port: 6000

  rules:
      - name: Launch playbook on start command
        condition: event.payload.command == 'start'
        action:
           run_job_template:
             organization: "Default"
             name: "Eda Playbook"
             eventSource: "{{ eventSource }}" 
