---
- name: Events from Wwindows_event_service_completo
  hosts: all
  sources:
   - name: Webhook
     ansible.eda.webhook:
       host: 0.0.0.0
       port: 6432

  rules:

    # - name: Captura todos los eventos
    #   condition: true
    #   action:
    #     debug:
    #       msg: "CESAR Evento genérico: {{ event }}"

    # - name: Print message
    #   condition: event.payload.issue.service == "not available"
    #   action:
    #     debug:
    #       msg: "Service not available detected!"

    - name: Inicializa el servicio windows. 
      condition: event.payload.issue.service == "not available" and event.payload.issue.state == "OPEN"
      action:
        run_job_template:
          organization: "Default"
          name: "windows_inicializa_servicio"
          job_args:
            extra_vars:
              vm_name: "{{ event.payload.issue.fqdn }}"
