- name: Events from Windows.
  hosts: all
  sources:
   - name: Webhook
     ansible.eda.webhook:
       host: 0.0.0.0
       port: 5000

  rules:
   - name: Inicializa el servicio windows. 
     condition: event.issue.service == "not available"
     action:
       run_job_template:
        organization: "Default"
        name: "windows_inicializa_servicio"
