---
- name: Creacion de incidente en servicenow.
  hosts: localhost 
  gather_facts: false  
  collections:
    - servicenow.itsm
    - servicenow 
  vars_files:
    - vars/vars.yml
  tasks: 

    - name: Create incident
      servicenow.itsm.incident:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
        caller: "{{ SN_USERNAME }}"
        state: new
        short_description: Demostración EDA ansible caida de servicio "{{ service_problem }}".
        description: Caso EDA ansible caida de servicio "{{ service_problem }}".
        impact: Low
        urgency: Low
      delegate_to: localhost
      register: incidente

    - name: Almacenamos variables importantes.
      ansible.builtin.set_stats:
        num_incidente: "{{ incidente.record.number }}"
    
