---
- name: Modifica y cierra el incidente en servicenow.
  hosts: localhost 
  gather_facts: false
  collections:
    - servicenow.itsm
    - servicenow 
  vars_files:
    - vars/vars.yml
  tasks: 

    - name: Actualizar incidente en ServiceNow
      servicenow.itsm.incident:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
        number: "{{ numero_incidente }}"
        short_description: "222 Me encuentro revisando el incidente prueba"
      register: incident_response

    - name: Mostrar la respuesta de la actualización
      ansible.builtin.debug:
        var: incident_response

    - name: Cambiar estado
      servicenow.itsm.incident:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
        #state: in_progress
        incident_state: "2"
        number: "{{ numero_incidente }}"

    - name: Cerrar incidente
      servicenow.itsm.incident:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
        #state: closed
        incident_state: "7"
        number: "{{ numero_incidente }}"
        close_code: "Solution provided"
        close_notes: "Se atiende el incidente de prueba y se procede a cerrar para la demo"
