---
- name: Modifica y cierra el incidente en servicenow.
  hosts: localhost 
  gather_facts: false
  collections:
    - servicenow.itsm
    - servicenow 
  vars_files:
    - vars/vars.yml
  tasks: 

    - name: Cambiar estado
      servicenow.itsm.incident:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
        #state: in_progress
        state: update
        number: "{{ num_incidente }}"
        other:
          incident_state: "2"

    - name: Cerrar incidente
      servicenow.itsm.incident:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
        state: update
        number: "{{ num_incidente }}"
        close_code: "Solution provided"
        close_notes: "Se atiende el incidente de prueba y se procede a cerrar para la demo, estado final del servicio {{ estado_final_servicio }}"
        other:
          incident_state: "7"
      when: estado_final_servicio == "running"