---
- name: Reinicio de servicio Windows. 
  hosts: "{{ vm_name }}"
  tasks: 
    
    - name: Reinicio de servicio.
      ansible.windows.win_service:
        name: "{{ service_problem }}"
        state: started

    - name: Valida estado de servicio.
      ansible.windows.win_service:
        name: "{{ service_problem }}"
      register: result_service    

    - name: Imprime resultado.
      ansible.builtin.debug: 
        msg: "El servicio quedo en estado: {{ result_service.state }}"

    - name: Almacenamos variables importantes.
      ansible.builtin.set_stats:
        estado_final_servicio: "{{ result_service.state }}"